Uniformizing error message and error message formatting
After launching GTG from flatpak I got an ill formatted error (showing `%s` instead of the proper values). It's due to a `raise ValueError` in `GTG/core/config.py`. After looking at that I started just fixing and uniformizing the error message formatting across GTG. Here's what's in the PR :
* uniformizing error message formating :
  * using the same string formatting mechanism
* raise `NotImplementedError` not `NotImplemented` which isn't an exception
```
>>> raise NotImplemented
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```
* do not explicitly reraise current error in an `except:` block, juste use bare `raise` statement
* raise error objects, not classes