GTK Backendtree: Use correct RGB to hex function
We only import `rgb_to_hex` but not `rgba_to_hex`, but the latter is
being used.
It seems to work with RGBA, so we just use the RGBA version.

Fixes the following error message:

      File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py", line 125, in on_backend_state_changed
        color = rgba_to_hex(color)
    NameError: name 'rgba_to_hex' is not defined